this_file: "alexnet_config_2.yaml"
# Directories definitions
datasets_root: "datasets"
dataset_train_dir: "datasets/train"
dataset_test_dir: "datasets/test"
dataset_val_dir: "datasets/val"

# Common Parameters
use_cuda: no

# Alexnet Parameters
input_shape: (227,227,3)
classes: 2
activation_func: 'relu'
activation_func_dense: 'softmax'
filters_l1: 96
filters_l2: 256
filters_l3: 384
filters_l4: 384
filters_l5: 256
kernel_size1: (11,11)
kernel_size2: (5,5)
kernel_size3: (3,3)
val_regularization: 0.0005
padding_conv: 'same'
padding_max_pool: 'valid'
strides_conv1: (4,4)
strides_conv2: (1,1)
strides_max_pool: (2,2)
pool_size: (3,3)
dropout_n1: 0.25
dropout_n2: 0.5
num_neural: 4096
directory: "../../train_models/"
