this_file: "make_videos.yaml"
# Directories definitions
short_clips_dir: "datasets/A3D/short_clips"
rec_videos_dir: "datasets/A3D/rec_videos"
videos_list: "datasets/A3D/video_list.txt"
# Parameters definitions
fps: 10
ext_in: ".jpg"
ext_out: ".mp4"
